name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v1
      - name: Make binaries
        uses: sosedoff/actions/golang-build@master
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: .release/
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .release/
