name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v1
      - name: Make binaries
        uses: izumin5210/action-go-crossbuild@v1.0.0
        with:
          package: ./cmd/tomato_exporter
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: ./dist
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
